name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PROJECT_ID: "499411"
      REGION: "us-central1"
      REPO_NAME: "notely-ar-repo"
      IMAGE_NAME: "notely"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      # GCP autentifikatsiya qismini ham kommentga oldik, 
      # chunki billing yo'qligi uchun xato berishi mumkin.
      # - name: Authenticate with GCP
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v2

      # - name: Configure Docker
      #   run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # - name: Build and Push Docker image
      #   run: |
      #     docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest .
      #     docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Run migrations
        run: ./scripts/migrateup.sh
        # Migration uchun DATABASE_URL sekret sifatida env'da berilgan.
