Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test ./...
      # Gosec o'rnatish
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      # Gosec tekshiruvi (bu qadam hozircha xato berishi kerak)
      - name: Run gosec
        run: gosec ./...
